spin_manifest_version = 2

[application]
name = "byte-bridge"
version = "0.1.0"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "Event Handler"

[application.trigger.redis]
address = "redis://localhost:6379"

[[trigger.redis]]
channel = "test"
component = "byte-bridge"

[component.byte-bridge]
source = "main.wasm"
allowed_outbound_hosts = []
[component.byte-bridge.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
