spin_manifest_version = 2

[application]
name = "nvms"
version = "0.1.0"
authors = ["Koosha Paridehpour <kooshapari@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test_run"

[component.nvms]
source = "target/wasm32-wasi/release/nvms.wasm"
allowed_outbound_hosts = []
[component.nvms.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
