[package]
name = "builder"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "Deployment/AWS Ops Only"
version = "0.1.0"
rust-version = "1.78"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
aws-config = "1.5.10"
aws-credential-types = "1.2.1"
aws-sdk-s3 = "1.65.0"
aws-types = "1.3.3"
bytes = "1.9.0"
chrono ={version ="0.4.39", features = ["serde"]}
json = "0.12.4"
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.133"
spin-sdk = "3.1.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio_with_wasm = { version = "0.0.0", features = ["full"] }
yaml-rust2 = "0.9.0"
rustls-native-certs = "0.8.1"
[dependencies.uuid]
version = "1.11.0"
features = [
    "serde",
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
[workspace]
