spin_manifest_version = 2

[application]
name = "nvms"
version = "0.1.0"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "UI Gen Config Parse and Systems builder IAC Platform"

[[trigger.http]]
route = "/..."
component = "nvms"

[component.nvms]
source = "main.wasm"
environment = {ENCRYPTION_KEY="${ENCRYPTION_KEY}", SERVICE_KEY="${SERVICE_KEY}"}
allowed_outbound_hosts = ["*://api.github.com:*", "*://github.com:*", "*://*.githubusercontent.com:*", "*://*.github.com:*","http://self"]
[component.nvms.build]
command = "tinygo build -target=wasip1 -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/provision"
component = "provisioner"

[component.provisioner]
source = "Provisioner/main.wasm"
environment = {ENCRYPTION_KEY="${ENCRYPTION_KEY}", SERVICE_KEY="${SERVICE_KEY}"}
allowed_outbound_hosts = ["*://api.github.com:*", "*://github.com:*", "*://*.githubusercontent.com:*", "*://*.github.com:*","http://self"]
[component.provisioner.build]
command = "tinygo build -target=wasip1 -gc=leaking -no-debug -o main.wasm main.go"
workdir = "Provisioner"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/build"
component = "builder"

[component.builder]
source = "Builder-R/target/wasm32-wasi/release/builder.wasm"
allowed_outbound_hosts = ["http://self","*://*:*"]
environment = { "RUSTFLAGS" = "--cfg target_arch=\"wasm32\"" }
[component.builder.build]
workdir = "Builder-R"
command = "cargo build --target wasm32-wasi --release"

watch = ["src/**/*.rs", "Cargo.toml"]

