package routes

import (
	"byteport/models"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// nvmsURL returns the NVMS service base URL from the NVMS_URL env var,
// falling back to the default localhost address.
func nvmsURL() string {
	if u := os.Getenv("NVMS_URL"); u != "" {
		return u
	}
	return "http://localhost:8443"
}

// nvmsToken reads the NanoVMS bearer token from NVMS_TOKEN env var.
// This token is generated by `nvms token mint` and stored at ~/.config/tokens.
func nvmsToken() string {
	return os.Getenv("NVMS_TOKEN")
}

// nvmsSandboxConfig is the request body NanoVMS expects at POST /v1/deploy.
type nvmsSandboxConfig struct {
	Name        string            `json:"name"`
	Image       string            `json:"image"`
	SandboxType string            `json:"sandbox_type"`
	Labels      map[string]string `json:"labels,omitempty"`
	Environment map[string]string `json:"env,omitempty"`
}

// nvmsSandboxResponse is the response NanoVMS returns after deploy.
type nvmsSandboxResponse struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	VMFlavor  string `json:"vm_flavor"`
	IPAddress string `json:"ip_address"`
}

func DeployProject(c *gin.Context) {
	var newProject models.Project
	if err := c.ShouldBindJSON(&newProject); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if err := newProject.BeforeSave(models.DB); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save project"})
		return
	}
	fmt.Println("Deploying project: ", newProject)

	// Translate BytePort Project → NanoVMS SandboxConfig
	sandboxCfg := nvmsSandboxConfig{
		Name:        newProject.Name,
		Image:       "alpine:latest", // default image
		SandboxType: "native",
		Labels: map[string]string{
			"byteport-project-id": newProject.UUID,
		},
	}

	jsonBody, err := json.Marshal(sandboxCfg)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to convert to sandbox config"})
		return
	}

	url := nvmsURL() + "/v1/deploy"
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonBody))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create request"})
		return
	}

	// Auth: NanoVMS expects Authorization header, not cookie.
	token := nvmsToken()
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to deploy project: " + err.Error()})
		return
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to read deploy response"})
		return
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error":  "Failed to deploy project",
			"status": resp.StatusCode,
			"body":   string(body),
		})
		return
	}

	// Translate NanoVMS SandboxResponse → BytePort Project
	var sandboxResp nvmsSandboxResponse
	if err := json.Unmarshal(body, &sandboxResp); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to parse sandbox response"})
		return
	}

	fmt.Println("Deployed sandbox: ", sandboxResp)

	newProject.SetDeploy(map[string]models.Instance{
		"default": {
			UUID:    sandboxResp.ID,
			Owner:   newProject.User.UUID,
			Name:    sandboxResp.Name,
			Status:  sandboxResp.Status,
			ResUUID: newProject.UUID,
		},
	})

	finalProject := models.Project{
		ID:           newProject.UUID,
		Owner:        newProject.User.UUID,
		Name:         newProject.Name,
		RepositoryID: newProject.RepositoryID,
		UUID:         newProject.UUID,
		Repository:   newProject.Repository,
		Readme:       newProject.Readme,
		Description:  newProject.Description,
		AccessURL:    newProject.AccessURL,
	}
	if finalProject.ID == "" {
		finalProject.ID = uuid.New().String()
	}
	if err := finalProject.BeforeSave(models.DB); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save project to DB"})
		return
	}
	if err := addNewProject(finalProject); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to add project to database"})
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"message":    "Success",
		"sandbox_id": sandboxResp.ID,
		"status":     sandboxResp.Status,
	})
}

func TerminateInstance(c *gin.Context) {
	user := c.MustGet("user").(models.User)
	var project models.Project
	if err := c.ShouldBindJSON(&project); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	project.User = user

	// NanoVMS stop expects POST /v1/stop?id=<sandbox_id> with query param.
	sandboxID := project.UUID
	if sandboxID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing sandbox ID"})
		return
	}

	url := fmt.Sprintf("%s/v1/stop?id=%s", nvmsURL(), sandboxID)
	req, err := http.NewRequest("POST", url, nil)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create request"})
		return
	}

	// Auth: NanoVMS expects Authorization header.
	token := nvmsToken()
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to stop sandbox: " + err.Error()})
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		c.JSON(http.StatusInternalServerError, gin.H{
			"error":  "Failed to stop sandbox",
			"status": resp.StatusCode,
			"body":   string(body),
		})
		return
	}

	if err := removeProject(project); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to remove project from database"})
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"message": "Success",
	})
}
