package routes

import (
	"byteport/models"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// nvmsURL returns the NVMS service base URL from the NVMS_URL env var,
// falling back to the default localhost address.
func nvmsURL() string {
	if u := os.Getenv("NVMS_URL"); u != "" {
		return u
	}
	return "http://localhost:8443"
}

// nvmsToken reads the NanoVMS bearer token from NVMS_TOKEN env var.
// This token is generated by `nvms token mint` and stored at ~/.config/tokens.
func nvmsToken() string {
	return os.Getenv("NVMS_TOKEN")
}

// nvmsHTTPClient is the shared HTTP client used for all NanoVMS requests.
// Sharing a single client lets it reuse keep-alive connections to NVMS and
// applies the production timeout uniformly. The previous per-handler
// `(&http.Client{}).Do` allocated a new client (and therefore a new
// transport) on every request, defeating keep-alive and applying no
// timeout — this helper fixes that anti-pattern.
var nvmsHTTPClient = &http.Client{Timeout: 30 * time.Second}

// nvmsRequest POSTs to the given NanoVMS path. body may be nil for empty
// requests (e.g. /v1/stop?id=<uuid>). The Bearer token from nvmsToken() is
// attached when set, and Content-Type: application/json is attached when
// body is non-nil.
//
// Returns the upstream status code and response body (already read in full)
// and any transport error. Callers translate non-2xx statuses into 500
// responses with the upstream body surfaced via respondErrorWithDetails.
func nvmsRequest(path string, body []byte) (status int, respBody []byte, err error) {
	req, err := http.NewRequest(http.MethodPost, nvmsURL()+path, bytes.NewReader(body))
	if err != nil {
		return 0, nil, fmt.Errorf("create nvms request: %w", err)
	}
	if token := nvmsToken(); token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := nvmsHTTPClient.Do(req)
	if err != nil {
		return 0, nil, fmt.Errorf("nvms request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err = io.ReadAll(resp.Body)
	if err != nil {
		return resp.StatusCode, nil, fmt.Errorf("read nvms response: %w", err)
	}
	return resp.StatusCode, respBody, nil
}

// nvmsSandboxConfig is the request body NanoVMS expects at POST /v1/deploy.
type nvmsSandboxConfig struct {
	Name        string            `json:"name"`
	Image       string            `json:"image"`
	SandboxType string            `json:"sandbox_type"`
	Labels      map[string]string `json:"labels,omitempty"`
	Environment map[string]string `json:"env,omitempty"`
}

// nvmsSandboxResponse is the response NanoVMS returns after deploy.
type nvmsSandboxResponse struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	VMFlavor  string `json:"vm_flavor"`
	IPAddress string `json:"ip_address"`
}

// deployRequest is the validated client contract for POST /deploy.
//
// Ownership is deliberately absent from the contract. `owner`, the project
// `uuid` and the project `id` are all derived from the authenticated session,
// so a caller cannot attribute a deployment to another account (or adopt an
// existing row) by putting `user`, `owner` or `uuid` in the body.
type deployRequest struct {
	Name         string             `json:"name" binding:"required"`
	Description  string             `json:"description"`
	Type         string             `json:"type"`
	Platform     string             `json:"platform"`
	Readme       string             `json:"readme"`
	RepositoryID string             `json:"repository_id"`
	Repository   *models.Repository `json:"repository"`
}

// repositoryID resolves the repository link, preferring the explicit
// `repository_id` and falling back to the id of an embedded `repository`
// object, which is the shape the web client posts.
func (r deployRequest) repositoryID() string {
	if r.RepositoryID != "" {
		return r.RepositoryID
	}
	if r.Repository != nil && r.Repository.ID != 0 {
		return strconv.FormatUint(uint64(r.Repository.ID), 10)
	}
	return ""
}

// terminateRequest is the validated client contract for POST /terminate.
type terminateRequest struct {
	UUID string `json:"uuid" binding:"required"`
}

// DeployProject creates a project owned by the authenticated caller and asks
// NanoVMS to provision a sandbox for it.
//
// The request is rejected with 400 before any database write or outbound call
// when the body is malformed or `name` is missing, so the endpoint never
// proxies an unvalidated body upstream.
func DeployProject(c *gin.Context) {
	user, ok := currentUser(c)
	if !ok {
		return
	}

	var req deployRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		respondBadRequest(c, "Invalid deploy request: "+err.Error())
		return
	}

	projectUUID := uuid.New().String()
	project := models.Project{
		UUID:         projectUUID,
		ID:           projectUUID,
		Owner:        user.UUID,
		Name:         req.Name,
		RepositoryID: req.repositoryID(),
		Readme:       req.Readme,
		Description:  req.Description,
		Type:         req.Type,
		Platform:     req.Platform,
	}
	if req.Repository != nil {
		project.Repository = *req.Repository
	}

	// Translate BytePort Project → NanoVMS SandboxConfig
	sandboxCfg := nvmsSandboxConfig{
		Name:        project.Name,
		Image:       "alpine:latest", // default image
		SandboxType: "native",
		Labels: map[string]string{
			"byteport-project-id": project.UUID,
		},
	}

	jsonBody, err := json.Marshal(sandboxCfg)
	if err != nil {
		respondInternalError(c, "Failed to convert to sandbox config")
		return
	}

	status, body, err := nvmsRequest("/v1/deploy", jsonBody)
	if err != nil {
		log.Printf("deploy: sandbox provisioning failed for project %s: %v", project.UUID, err)
		respondInternalError(c, "Failed to deploy project: "+err.Error())
		return
	}

	if status != http.StatusOK && status != http.StatusCreated {
		log.Printf("deploy: sandbox provisioning rejected project %s with status %d", project.UUID, status)
		respondErrorWithDetails(c, http.StatusInternalServerError, "Failed to deploy project", gin.H{
			"status": status,
			"body":   string(body),
		})
		return
	}

	// Translate NanoVMS SandboxResponse → BytePort Project
	var sandboxResp nvmsSandboxResponse
	if err := json.Unmarshal(body, &sandboxResp); err != nil {
		respondInternalError(c, "Failed to parse sandbox response")
		return
	}

	project.SetDeploy(map[string]models.Instance{
		"default": {
			UUID:    sandboxResp.ID,
			Owner:   user.UUID,
			Name:    sandboxResp.Name,
			Status:  sandboxResp.Status,
			ResUUID: project.UUID,
		},
	})

	if err := project.BeforeSave(models.DB); err != nil {
		respondInternalError(c, "Failed to save project to DB")
		return
	}
	if err := addNewProject(project); err != nil {
		respondInternalError(c, "Failed to add project to database")
		return
	}

	recordDeploy()
	log.Printf("deploy: project %s provisioned sandbox %s (%s)", project.UUID, sandboxResp.ID, sandboxResp.Status)
	c.JSON(http.StatusOK, gin.H{
		"message":    "Success",
		"sandbox_id": sandboxResp.ID,
		"status":     sandboxResp.Status,
	})
}

// TerminateInstance stops the sandbox behind a project and deletes the project.
//
// Both the stop and the delete are scoped to the authenticated owner: a caller
// can only terminate a project it owns, and a project owned by somebody else is
// reported as missing rather than forbidden so existence is not leaked.
func TerminateInstance(c *gin.Context) {
	user, ok := currentUser(c)
	if !ok {
		return
	}

	var req terminateRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		respondBadRequest(c, "Invalid terminate request: "+err.Error())
		return
	}

	var project models.Project
	if err := models.DB.Where("uuid = ? AND owner = ?", req.UUID, user.UUID).First(&project).Error; err != nil {
		respondNotFound(c, "Project not found")
		return
	}

	// NanoVMS stop expects POST /v1/stop?id=<sandbox_id> with query param.
	sandboxID := project.UUID
	if sandboxID == "" {
		respondBadRequest(c, "missing sandbox ID")
		return
	}

	stopPath := fmt.Sprintf("/v1/stop?id=%s", url.QueryEscape(sandboxID))
	status, body, err := nvmsRequest(stopPath, nil)
	if err != nil {
		log.Printf("terminate: stopping sandbox for project %s failed: %v", project.UUID, err)
		respondInternalError(c, "Failed to stop sandbox: "+err.Error())
		return
	}

	if status != http.StatusOK {
		log.Printf("terminate: sandbox stop for project %s returned status %d", project.UUID, status)
		respondErrorWithDetails(c, http.StatusInternalServerError, "Failed to stop sandbox", gin.H{
			"status": status,
			"body":   string(body),
		})
		return
	}

	if err := removeProject(project); err != nil {
		respondInternalError(c, "Failed to remove project from database")
		return
	}

	recordSandboxStopped()
	c.JSON(http.StatusOK, gin.H{
		"message": "Success",
	})
}
