# RPM spec — BytePort CLI
#
# Build:
#   rpmbuild -ba byteport.spec
# Or, with mock (recommended for isolation):
#   mock -r fedora-39-x86_64 byteport.src.rpm
#
# This spec follows Fedora packaging guidelines:
#   https://docs.fedoraproject.org/en-US/packaging-guidelines/
# License: Apache-2.0
# Upstream: https://github.com/KooshaPari/BytePort

Name:           byteport
Version:        0.1.0
Release:        1%{?dist}
Summary:        Self-hosted IaC + portfolio platform CLI

# Apache-2.0 with exceptions for bundled third-party assets.
# SPDX short-form identifiers:
#   https://spdx.org/licenses/
License:        Apache-2.0
URL:            https://github.com/KooshaPari/BytePort

Source0:        %{url}/archive/v%{version}/byteport-%{version}.tar.gz
# Source1 (if needed in future): upstream Cargo.lock for reproducibility.

# Build dependencies — declared in `cargo` and `rust` policy packages
# so Fedora's buildroot install step picks them up automatically.
BuildRequires:  cargo
BuildRequires:  rust >= 1.75
BuildRequires:  openssl-devel
BuildRequires:  pkgconfig
BuildRequires:  make
BuildRequires:  gcc

# Runtime dependencies — generated by `rpm -E '%{dependencies:...}'` style
# macros when expanded against the resulting ELF, but we keep an explicit
# `Requires` here to mirror the Debian control file.
Requires:       libc.so.6()(64bit)
Requires:       libssl.so.3()(64bit)
Requires:       ca-certificates

# Multi-arch build flag (Fedora-only spec tag).
ExclusiveArch:  %{rust_arches}

# Disable debug info collection for the cli binary — we ship a stripped
# binary in release. Override with `%global _enable_debug_package 0`
# if your distribution policy requires -debuginfo subpackages.
%global _enable_debug_package 0
%global __strip /bin/true

%description
BytePort is a self-hosted Infrastructure-as-Code deployment + portfolio
platform for developer projects. Define one manifest (`odin.nvms`) at your
repo root and BytePort provisions a MicroVM-backed deployment (via the
`nvms` Spin runtime), registers the resulting endpoints with a portfolio
site, and uses an LLM to generate showcase metadata for each project.

This package ships the `byteport` command-line client which drives the
manifest engine, manages local deploys, and surfaces diagnostics — all
on top of `odin.nvms` as the single source of truth. The graphical
desktop shell is shipped separately as a Tauri-built AppImage / deb
under `frontend/web/src-tauri/`.

Security highlights: AES-256-CFB for secrets at rest, Argon2id for
password hashing, PASETO v2 for session tokens, SSRF-safe HTTP client
for user-supplied URLs. Traces exportable via OpenTelemetry.

License: Apache-2.0.
Homepage: https://byteport.dev
Source: https://github.com/KooshaPari/BytePort

%prep
# Fedpkg will generate the source tarball; `--no-quiet` is set so
# CI logs show what's happening.
%autosetup -n byteport-%{version} -p1

%build
# Fedora's rpm-build macros provide `%cargo_build` which sets
# RUSTFLAGS, CARGO_HOME, etc. correctly. We override the manifest
# path because the cli binary lives under crates/byteport-cli/.
export CARGO_TERM_COLOR=always
%cargo_build --manifest-path crates/byteport-cli/Cargo.toml --release --locked

%install
# Clean installed bits from prior runs (mock builds).
rm -rf %{buildroot}
install -Dm 0755 target/release/byteport \
    %{buildroot}%{_bindir}/byteport

# Install manpage if present (generated by clap at build time when --generate
# is enabled; for now we ship a placeholder) — fallback to no-op silently.
%if 0%{?fedora} || 0%{?rhel}
install -Dm 0644 LICENSE %{buildroot}%{_licensedir}/%{name}/LICENSE || true
%endif

%files
%defattr(-, root, root, 0755)
%license LICENSE
%{_bindir}/byteport

%changelog
* Thu Jul 04 2026 KooshaPari <hi@kooshapari.dev> - 0.1.0-1
- Initial RPM package for BytePort CLI.
- Self-contained build of crates/byteport-cli from the workspace.
- Single binary install at %{_bindir}/byteport; Apache-2.0 license.
