spin_manifest_version = 2

[application]
name = "nvms"
version = "0.1.0"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "UI Gen Config Parse and Systems builder IAC Platform"

[[trigger.http]]
route = "/..."
component = "nvms"

[component.nvms]
source = "main.wasm"
files = [{ source = "examples/", destination = "/" }]
[component.nvms.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/test"
component = "test"

[component.test]
source = "test/main.wasm"
files = [{ source = "examples/", destination = "/t" }]
allowed_outbound_hosts = []
[component.test.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "test"
watch = ["**/*.go", "go.mod"]
