spin_manifest_version = 2

[application]
name = "nvms"
version = "0.1.0"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "UI Gen Config Parse and Systems builder IAC Platform"

[[trigger.http]]
route = "/..."
component = "nvms"

[component.nvms]
source = "main.wasm"
allowed_outbound_hosts = []
[component.nvms.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/nvms/deploy"
component = "deploy"

[component.deploy]
source = "deploy/main.wasm"
allowed_outbound_hosts = []
[component.deploy.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "deploy"
watch = ["**/*.go", "go.mod"]
