spin_manifest_version = 2

[application]
name = "nvms"
version = "0.1.0"
authors = ["KooshaPari <kooshapari@gmail.com>"]
description = "UI Gen Config Parse and Systems builder IAC Platform"

[[trigger.http]]
route = "/..."
component = "nvms"

[[component]]
id ="nvms"
source = "/deploy/nvms.wasm"\
[component.trigger]

allowed_outbound_hosts = []
files = [{ source = "examples", destination = "/examples" }]
[component.nvms.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

