//! Placeholder for the generated `#[zbus::dbus_interface]` expansion.
//!
//! The `zbus::dbus_interface` proc-macro emits a sibling module
//! (`<trait_name>_short`) and an inline `dbus::Interface` impl per
//! annotated trait. We don't ship that expansion in source form here;
//! the real impl will live behind the `dbus::LinuxBridge1` trait and
//! be regenerated by `cargo build` on every Linux compile.
//!
//! This file exists so:
//! - `cargo doc` produces a complete API map for the crate.
//! - The codegen pipeline (B6 of v8.2) has a stable anchor point.
//! - Future maintainers can grep for `codegen` to find the generated
//!   introspection XML without spelunking through `target/`.
//!
//! On every target this module is empty; the only thing it exports is
//! the introspection XML stub consumed by [`introspection_xml`].

/// Introspection XML for `org.byteport.LinuxBridge1`.
///
/// Kept here (rather than auto-generated at compile time) so companion
/// app authors can reference a stable file path while the scaffold is
/// in place. When the real interface ships, this string will be moved
/// behind a `build.rs`-emitted `include!()`.
pub const INTERFACE_INTROSPECTION_XML: &str = r##"<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node name="/org/byteport/LinuxBridge1">
  <interface name="org.byteport.LinuxBridge1">
    <method name="Handoff">
      <arg name="item_count" type="t" direction="in"/>
      <arg name="session_id" type="t" direction="out"/>
    </method>
    <method name="Ping">
      <arg name="reply" type="s" direction="out"/>
    </method>
    <signal name="BytesReceived">
      <arg name="session_id" type="t"/>
      <arg name="byte_count" type="t"/>
    </signal>
  </interface>
</node>
"##;

/// Convenience accessor used by tests and the future build script.
#[must_use]
pub fn introspection_xml() -> &'static str {
    INTERFACE_INTROSPECTION_XML
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn introspection_xml_is_well_formed_envelope() {
        let xml = introspection_xml();
        assert!(xml.contains("<!DOCTYPE node"));
        assert!(xml.contains("org.byteport.LinuxBridge1"));
        assert!(xml.contains("<method name=\"Handoff\""));
        assert!(xml.contains("<method name=\"Ping\""));
        assert!(xml.contains("<signal name=\"BytesReceived\""));
    }
}
